import { statutory_reqs } from "./enum"


export const ApiSequence = {
    SEARCH: 'search_full_catalog_refresh',
    ON_SEARCH: 'on_search_full_catalog_refresh',
    INC_SEARCH: 'search_inc_refresh',
    INC_ONSEARCH: 'on_search_inc_refresh',
    SELECT: 'select',
    ON_SELECT: 'on_select',
    INIT: 'init',
    ON_INIT: 'on_init',
    CONFIRM: 'confirm',
    ON_CONFIRM: 'on_confirm',
    CANCEL: 'cancel',
    ON_CANCEL: 'on_cancel',
    TRACK: 'track',
    ON_TRACK: 'on_track',
    STATUS: 'status',
    ON_STATUS_PENDING: 'on_status_pending',
    ON_STATUS_PACKED: 'on_status_packed',
    ON_STATUS_PICKED: 'on_status_picked',
    ON_STATUS_OUT_FOR_DELIVERY: 'on_status_out_for_delivery',
    ON_STATUS_DELIVERED: 'on_status_delivered',
    ON_STATUS_RTO_DELIVERED: 'on_status_rto_delivered/disposed',
    ON_UPDATE_PART_CANCEL: 'on_update_part_cancel',
    UPDATE: 'update',
    UPDATE_REVERSE_QC: 'update_reverse_qc',
    UPDATE_LIQUIDATED: 'update_liquidated',
    UPDATE_SETTLEMENT: 'update_settlement',
    UPDATE_SETTLEMENT_PART_CANCEL: 'update_settlement_part_cancel',
    UPDATE_SETTLEMENT_REVERSE_QC: 'update_settlement_reverse_qc',
    UPDATE_SETTLEMENT_LIQUIDATED: 'update_settlement_liquidated',
    ON_UPDATE: 'on_update',
    ON_UPDATE_INTERIM: 'on_update_interim',
    ON_UPDATE_INTERIM_REVERSE_QC: 'on_update_interim_reverse_qc',
    ON_UPDATE_INTERIM_LIQUIDATED: 'on_update_interim_liquidated',
    ON_UPDATE_PICKED: 'on_update_picked',
    ON_UPDATE_DELIVERED: 'on_update_delivered',
    ON_UPDATE_APPROVAL: 'on_update_approval',
    ON_UPDATE_LIQUIDATED: 'on_update_liquidated',
    SELECT_OUT_OF_STOCK: 'select_out_of_stock',
    ON_SELECT_OUT_OF_STOCK: 'on_select_out_of_stock',
    CATALOG_REJECTION: 'catalog_rejection'
}

export default Object.freeze({
    RET_CONTEXT_TTL: 'PT30S',
    CONTEXT_ACTION: 'action',
    DB_PATH: 'dbfiles',
    DECIMAL_PRECISION: 6,
    ORDER_PICKED: 'Order-picked-up',
    ORDER_PACKED: 'Packed',
    ORDER_OUT_FOR_DELIVERY: 'Out-for-delivery',
    ORDER_DELIVERED: 'Order-delivered',
    SEARCH: 'search',
    INC_SEARCH: 'inc_search',
    ON_SEARCH: 'on_search',
    ON_SEARCHINC: 'on_search_inc',
    SELECT: 'select',
    ON_SELECT: 'on_select',
    SELECT_OUT_OF_STOCK: 'select_out_of_stock',
    ON_SELECT_OUT_OF_STOCK: 'on_select_out_of_stock',
    CONFIRM: 'confirm',
    ON_CONFIRM: 'on_confirm',
    INIT: 'init',
    ON_INIT: 'on_init',
    STATUS: 'status',
    UPDATE: 'update',
    ON_UPDATE: 'on_update',
    ON_UPDATE_INTERIM: 'on_update_interim',
    ON_STATUS: 'on_status',
    ON_STATUS_PENDING: 'on_status_pending',
    ON_STATUS_PACKED: 'on_status_packed',
    ON_STATUS_PICKED: 'on_status_picked',
    ON_STATUS_OUT_FOR_DELIVERY: 'on_status_out_for_delivery',
    ON_STATUS_DELIVERED: 'on_status_delivered',
    ON_STATUS_RTO_DELIVERED: 'on_status_rto_delivered/disposed',
    CANCEL: 'cancel',
    ON_CANCEL: 'on_cancel',
    ON_CANCEL_RTO: 'on_cancel_rto',
    TRACK: 'track',
    ON_TRACK: 'on_track',
    SUPPORT: 'support',
    ON_SUPPORT: 'on_support',
    RET_ISSUE: 'issue',
    RET_ONISSUE: 'on_issue',
    RET_ISSUE_STATUS: 'issue_status',
    RET_ONISSUE_STATUS: 'on_issue_status',
    RECEIVER_RECON: 'receiver_recon',
    ON_RECEIVER_RECON: 'on_receiver_recon',
    SETTLE: 'settle',
    ON_SETTLE: 'on_settle',
    REPORT: 'report',
    ON_REPORT: 'on_report',
    RECON: 'recon',
    ON_RECON: 'on_recon',
    CATALOG_REJECTION: 'catalog_rejection',
    "ISSUE_1": "issue_1",
    "ON_ISSUE_1": "on_issue_1",
    "ON_ISSUE_2": "on_issue_2",
    "ISSUE_2": "issue_2",
    "ON_ISSUE_3": "on_issue_3",
    "ON_ISSUE_4": "on_issue_4",
    "ISSUE_3": "issue_3",
    "ON_ISSUE_5": "on_issue_5",
    "ON_ISSUE_6": "on_issue_6",
    "ISSUE_4": "issue_4",
    "ON_ISSUE_7": "on_issue_7",
    "ISSUE_5": "issue_5",
})

export const PAYMENT_STATUS = {
    PAID: 'PAID',
    NOT_PAID: 'NOT-PAID',
}


export const groceryCategoryMappingWithStatutory: { [key: string]: statutory_reqs } = {
    "Bakery, Cakes & Dairy": statutory_reqs.PrepackagedFood,
    "Dairy and Cheese": statutory_reqs.PrepackagedFood,
    "Snacks, Dry Fruits, Nuts": statutory_reqs.PrepackagedFood,
    "Cereals and Breakfast": statutory_reqs.PrepackagedFood,
    "Sauces, Spreads and Dips": statutory_reqs.PrepackagedFood,
    "Chocolates and Biscuits": statutory_reqs.PrepackagedFood,
    "Tinned and Processed Food": statutory_reqs.PrepackagedFood,
    "Energy and Soft Drinks": statutory_reqs.PrepackagedFood,
    "Fruit Juices and Fruit Drinks": statutory_reqs.PrepackagedFood,
    "Snacks and Namkeen": statutory_reqs.PrepackagedFood,
    "Ready to Cook and Eat": statutory_reqs.PrepackagedFood,
    "Pickles and Chutney": statutory_reqs.PrepackagedFood,
    "Indian Sweets": statutory_reqs.PrepackagedFood,
    "Frozen Snacks": statutory_reqs.PrepackagedFood,
    "Masala & Seasoning": statutory_reqs.PackagedCommodities,
    "Oil & Ghee": statutory_reqs.PackagedCommodities,
    "Eggs, Meat & Fish": statutory_reqs.PackagedCommodities,
    "Pet Care": statutory_reqs.PackagedCommodities,
    "Pasta, Soup and Noodles": statutory_reqs.PackagedCommodities,
    "Cooking and Baking Needs": statutory_reqs.PackagedCommodities,
    "Atta, Flours and Sooji": statutory_reqs.PackagedCommodities,
    "Rice and Rice Products": statutory_reqs.PackagedCommodities,
    "Dals and Pulses": statutory_reqs.PackagedCommodities,
    "Salt, Sugar and Jaggery": statutory_reqs.PackagedCommodities,
    "Tea and Coffee": statutory_reqs.PackagedCommodities,
    "Fruits and Vegetables": statutory_reqs.None,
    "Water": statutory_reqs.None,
    "Frozen Vegetables": statutory_reqs.None,
    "Gift Voucher": statutory_reqs.None
};


export const ffCategory = [["Immediate Delivery", "Standard Delivery", "Express Delivery"], ["Takeaway", "Kerbside"]]