codes:
  - code: 100
    action_id: search_seller_pagination
    action: search
    default: TRV14/2.0.0/search/search_pagination/default.yaml
    message_id: true
  - code: 101
    action_id: on_search_seller_pagination_1
    action: on_search
    default: TRV14/2.0.0/on_search/on_search_seller_pagination/on_search_seller_pagination_1/default.yaml
    message_id: false
  - code: 102
    action_id: on_search_seller_pagination_2
    action: on_search
    default: TRV14/2.0.0/on_search/on_search_seller_pagination/on_search_seller_pagination_2/default.yaml
    message_id: true
  - code: 103
    action_id: on_search_seller_pagination_3
    action: on_search
    default: TRV14/2.0.0/on_search/on_search_seller_pagination/on_search_seller_pagination_3/default.yaml
    message_id: true
  - code: 104
    action_id: search_incremental_pull
    action: search
    default: TRV14/2.0.0/search/search_incremental_pull/default.yaml
    message_id: true
  - code: 105
    action_id: on_search_incremental_pull_1
    action: on_search
    default: TRV14/2.0.0/on_search/on_search_incremental_pull/on_search_incremental_pull_1/default.yaml
    message_id: false
  - code: 106
    action_id: on_search_incremental_pull_2
    action: on_search
    default: TRV14/2.0.0/on_search/on_search_incremental_pull/on_search_incremental_pull_2/default.yaml
    message_id: true
  - code: 107
    action_id: on_search_incremental_pull_3
    action: on_search
    default: TRV14/2.0.0/on_search/on_search_incremental_pull/on_search_incremental_pull_3/default.yaml
    message_id: true
  - code: 108
    action_id: select
    action: select
    default: TRV14/2.0.0/select/default.yaml
    message_id: true
  - code: 109
    action_id: on_select
    action: on_select
    default: TRV14/2.0.0/on_select/default.yaml
    message_id: false
  - code: 110
    action_id: on_select_without_form
    action: on_select
    default: TRV14/2.0.0/on_select_without_form/default.yaml
    message_id: false
  - code: 111
    action_id: init
    action: init
    default: TRV14/2.0.0/init/default.yaml
    message_id: true
  - code: 112
    action_id: on_init
    action: on_init
    default: TRV14/2.0.0/on_init/default.yaml
    message_id: false
  - code: 113
    action_id: confirm
    action: confirm
    default: TRV14/2.0.0/confirm/default.yaml
    message_id: true
  - code: 114
    action_id: on_confirm
    action: on_confirm
    default: TRV14/2.0.0/on_confirm/default.yaml
    message_id: false
  - code: 115
    action_id: status
    action: status
    default: TRV14/2.0.0/status/default.yaml
    message_id: true
  - code: 116
    action_id: on_status
    action: on_status
    default: TRV14/2.0.0/on_status/default.yaml
    message_id: false
  - code: 116
    action_id: on_status_unsoliciated
    action: on_status
    default: TRV14/2.0.0/on_status/default.yaml
    message_id: true  
  - code: 117
    action_id: cancel
    action: cancel
    default: TRV14/2.0.0/cancel/default.yaml
    message_id: true
  - code: 118
    action_id: on_cancel
    action: on_cancel
    default: TRV14/2.0.0/on_cancel/default.yaml
    message_id: false
  - code: 119
    action_id: on_confirm_technical_cancellation
    action: on_confirm
    default: TRV14/2.0.0/on_confirm/on_confirm_technical_cancellation/default.yaml
    message_id: false
  - code: 120
    action_id: status_technical_cancellation
    action: status
    default: TRV14/2.0.0/status/status_technical_cancellation/default.yaml
    message_id: true
  - code: 121
    action_id: on_status_technical_cancellation
    action: on_status
    default: TRV14/2.0.0/on_status/on_status_technical_cancellation/default.yaml
    message_id: false
  - code: 122
    action_id: cancel_soft_technical_cancellation
    action: cancel
    default: TRV14/2.0.0/cancel/cancel_soft_technical_cancellation/default.yaml
    message_id: true
  - code: 123
    action_id: on_cancel_soft_technical_cancellation
    action: on_cancel
    default: TRV14/2.0.0/on_cancel/on_cancel_soft_technical_cancellation/default.yaml
    message_id: false
  - code: 124
    action_id: cancel_confirm_technical_cancellation
    action: cancel
    default: TRV14/2.0.0/cancel/cancel_confirm_technical_cancellation/default.yaml
    message_id: true
  - code: 125
    action_id: on_cancel_confirm_technical_cancellation
    action: on_cancel
    default: TRV14/2.0.0/on_cancel/on_cancel_confirm_technical_cancellation/default.yaml
    message_id: false
  - code: 126
    action_id: on_confirm_user_cancellation
    action: on_confirm
    default: TRV14/2.0.0/on_confirm/on_confirm_user_cancellation/default.yaml
    message_id: false
  - code: 127
    action_id: status_user_cancellation
    action: status
    default: TRV14/2.0.0/status/status_user_cancellation/default.yaml
    message_id: true
  - code: 128
    action_id: on_status_user_cancellation
    action: on_status
    default: TRV14/2.0.0/on_status/on_status_user_cancellation/default.yaml
    message_id: false
  - code: 129
    action_id: cancel_soft_user_cancellation
    action: cancel
    default: TRV14/2.0.0/cancel/cancel_soft_user_cancellation/default.yaml
    message_id: true
  - code: 130
    action_id: on_cancel_soft_user_cancellation
    action: on_cancel
    default: TRV14/2.0.0/on_cancel/on_cancel_soft_user_cancellation/default.yaml
    message_id: false
  - code: 131
    action_id: cancel_confirm_user_cancellation
    action: cancel
    default: TRV14/2.0.0/cancel/cancel_confirm_user_cancellation/default.yaml
    message_id: true
  - code: 132
    action_id: on_cancel_confirm_user_cancellation
    action: on_cancel
    default: TRV14/2.0.0/on_cancel/on_cancel_confirm_user_cancellation/default.yaml
    message_id: false
  - code: 133
    action_id: on_confirm_partial_cancellation
    action: on_confirm
    default: TRV14/2.0.0/on_confirm/on_confirm_partial_cancellation/default.yaml
    message_id: false
  - code: 134
    action_id: cancel_soft_partial_cancellation
    action: cancel
    default: TRV14/2.0.0/cancel/cancel_soft_partial_cancellation/default.yaml
    message_id: true
  - code: 135
    action_id: on_cancel_soft_partial_cancellation
    action: on_cancel
    default: TRV14/2.0.0/on_cancel/on_cancel_soft_partial_cancellation/default.yaml
    message_id: false
  - code: 136
    action_id: select_form_submission
    action: select
    default: TRV14/2.0.0/select_form_submission/default.yaml
    message_id: true
  - code: 189
    action_id: select_form_submission_cultural
    action: select
    default: TRV14/2.0.0/select_form_submission_cultural/default.yaml
    message_id: true
  - code: 137
    action_id: on_select_form_submission
    action: on_select
    default: TRV14/2.0.0/on_select_form_submission/default.yaml
    message_id: false
  - code: 191
    action_id: on_select_submission_cultural
    action: on_select
    default: TRV14/2.0.0/on_select_cultural/default.yaml
    message_id: false
  - code: 190
    action_id: on_select_form_submission_culture
    action: on_select
    default: TRV14/2.0.0/on_select_form_submission_culture/default.yaml
    message_id: false
  - code: 138
    action_id: on_cancel_rejected
    action: on_cancel
    default: TRV14/2.0.0/on_cancel/on_cancel_rejected/default.yaml
    message_id: false
  - code: 139
    action_id: select_partial_cancellation
    action: select
    default: TRV14/2.0.0/select/default.yaml
    message_id: true
  - code: 144
    action_id: select_for_partial_cancellation
    action: select
    default: TRV14/2.0.0/select_for_partial_cancellation/default.yaml
    message_id: true
  - code: 140
    action_id: update_soft_partial_cancellation
    action: update
    default: TRV14/2.0.0/update/update_soft_partial_cancellation/default.yaml
    message_id: true
  - code: 141
    action_id: on_update_soft_partial_cancellation
    action: on_update
    default: TRV14/2.0.0/on_update/on_update_soft_partial_cancellation/default.yaml
    message_id: false
  - code: 142
    action_id: update_confirm_partial_cancellation
    action: update
    default: TRV14/2.0.0/update/update_confirm_partial_cancellation/default.yaml
    message_id: true
  - code: 143
    action_id: on_update_confirm_partial_cancellation
    action: on_update
    default: TRV14/2.0.0/on_update/on_update_confirm_partial_cancellation/default.yaml
    message_id: false

     # ___________________IMG FLOW BUS 201_____________________

  - code: 316
    action_id: issue_open
    action: issue
    default: TRV14/2.0.0/issue/issue_open/default.yaml
    message_id: true
  - code: 317
    action_id: on_issue_processing
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_processing/default.yaml
    message_id: false
  - code: 318
    action_id: on_issue_need_more_info
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_need_more_info/default.yaml
    message_id: true
  - code: 319
    action_id: issue_info_provided
    action: issue
    default: TRV14/2.0.0/issue/issue_info_provided/default.yaml
    message_id: true
  - code: 320
    action_id: on_issue_provided
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_provided/default.yaml
    message_id: false
  - code: 321
    action_id: on_issue_resolution
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_resolution/default.yaml
    message_id: true
  - code: 322
    action_id: issue_resolution_accept
    action: issue
    default: TRV14/2.0.0/issue/issue_resolution_accept/default.yaml
    message_id: true
  - code: 323
    action_id: on_issue_resolved
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_resolved/default.yaml
    message_id: true
  - code: 324
    action_id: issue_close
    action: issue
    default: TRV14/2.0.0/issue/issue_close/default.yaml
    message_id: true
  # - code: 163
  #   action_id: issue_close_thumbs_Down
  #   action: issue
  #   default: issue/issue_close/default.yaml
  #   message_id: true
  - code: 325
    action_id: issue_open_2
    action: issue
    default: TRV14/2.0.0/issue/issue_open_2/default.yaml
    message_id: true
  - code: 326
    action_id: issue_resolution_reject
    action: issue
    default: TRV14/2.0.0/issue/issue_resolution_accept/default.yaml
    message_id: true
  - code: 326
    action_id: on_issue_processing_1
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_processing/default.yaml
    message_id: false
  - code: 327
    action_id: on_issue_processing_2
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_processing/default.yaml
    message_id: false
  - code: 328
    action_id: issue_escalate
    action: issue
    default: TRV14/2.0.0/issue/issue_open/default.yaml
    message_id: true
  - code: 329
    action_id: on_issue_resolution_1
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_resolution/default.yaml
    message_id: true
  - code: 330
    action_id: on_issue_resolution_2
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_resolution/default.yaml
    message_id: true
  - code: 331
    action_id: on_issue_resolution_igm_3
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_resolution/default.yaml
    message_id: true
  - code: 332
    action_id: issue_resolution_accept_igm_3
    action: issue
    default: TRV14/2.0.0/issue/issue_resolution_accept/default.yaml
    message_id: true
  - code: 333
    action_id: on_issue_resolved_igm_3
    action: on_issue
    default: TRV14/2.0.0/on_issue/on_issue_resolved/default.yaml
    message_id: true
  - code: 334
    action_id: issue_close_igm_3
    action: issue
    default: TRV14/2.0.0/issue/issue_close/default.yaml
    message_id: true
  - code: 335
    action_id: on_update_igm_return
    action: on_update
    default: TRV14/2.0.0/on_update/on_update_return_igm/default.yaml
    message_id: true
  - code: 336
    action_id: on_update_igm_replacement
    action: on_update
    default: TRV14/2.0.0/on_update/on_update_replacement_igm/default.yaml
    message_id: true
  - code: 337
    action_id: on_status_igm_3
    action: on_status
    default: TRV14/2.0.0/on_status/on_status_order_delivered/default.yaml
    message_id: true


