save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  payments: "$.message.order.payments[*]"
  created_at: "$.context.timestamp"
  updated_at: "$.context.timestamp"
  last_call_ttl: "$.context.ttl"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"

