save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  order: "$.message.order"
  claim_doc_url: "$.message.order.documents[?(@.descriptor.code=='CLAIM_DOC')].url"
  renew_doc_url: "$.message.order.documents[?(@.descriptor.code=='RENEW_DOC')].url"