save-data:
  payments: "$.message.order.payments[*]"
  payment_id: "$.message.order.payments[*].id"
  price: "$.message.order.quote.price.value"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.order.quote"
  provider: "$.message.order.provider"
  time_range: "$.message.order.provider.time"
 