save-data:
  order_id: "$.message.order.id"
  status: "$.message.order.status"
  updated_payments: "$.message.order.payments[*]"
  created_at: "$.message.order.created_at"
  items: "$.message.order.items[*]"
  provider: "$.message.order.provider"
  fulfillments: "$.message.order.fulfillments[*]"
  cancellation_terms: "$.message.order.cancellation_terms[*]"
  billing: "$.message.order.billing"
  quote: "$.message.order.quote"
  tags: "$.message.order.tags[*]"