save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  bap_id: "$.context.bap_id"
  items: "$.message.catalog.providers[*].items[*]"
  provider_id: "$.message.catalog.providers[0].id"
  item: "$.message.catalog.providers[0].items[0]"
  fulfillments: "$.message.catalog.providers[0].fulfillments[*]"
  fullfillment_ids: "$.message.catalog.providers[0].fulfillments[*].id"
  fulfillment_id: "$.message.catalog.providers[0].fulfillments[0].id"
  selected_category_ids: "$.message.catalog.providers[0].items[0].category_ids"
  selected_provider: "$.message.catalog.providers[0]"
  form_id: "$.message.catalog.providers[0].items[0].xinput.form.id"
  individual_information_form: "$..form.url"
 