save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  collected_by: "$.message.intent.payment.collected_by" 
  tags: "$.message.intent.tags"
  provider_id: "$.message.intent.provider.id"
  provider: "$.message.intent.provider"
  item_id: "$.message.intent.provider.items[*].id"
  start_time: "$.message.intent.fulfillment.stops[?(@.type=='START')].time.range.start"
  end_time: "$.message.intent.fulfillment.stops[?(@.type=='START')].time.range.end"
  city_code: "$.context.location.city.code"