save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  
  # Update specific data
  update_target: "$.message.update_target"
  cancellation_reason: "$.message.order.cancellation.reason"
  
  # Updated item quantities (for partial cancellation)
  updated_items: "$.message.order.items[*]"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
