codes:
  # Search flows (500-501)
  - code: 500
    action_id: search
    action: search
    default: FIS14/mutual-funds/2.1.0/search/default.yaml
    message_id: true
  - code: 501
    action_id: on_search
    action: on_search
    default: FIS14/mutual-funds/2.1.0/on_search/default.yaml
    message_id: false

  # Search incremental flow
  - code: 512
    action_id: search_incremental_pull
    action: search
    default: FIS14/mutual-funds/2.1.0/search_incremental_pull/default.yaml
    message_id: true
  - code: 513
    action_id: on_search_incremental_pull
    action: on_search
    default: FIS14/mutual-funds/2.1.0/on_search_incremental_pull/default.yaml
    message_id: false
    
  # SIP Creation flows (502-513)
  - code: 502
    action_id: select
    action: select
    default: FIS14/mutual-funds/2.1.0/select/default.yaml
    message_id: true
  - code: 503
    action_id: on_select
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select/default.yaml
    message_id: false

  - code: 515
    action_id: on_select_existing_folio
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_existing_folio/default.yaml
    message_id: false
        
  - code: 5021
    action_id: select_2
    action: select
    default: FIS14/mutual-funds/2.1.0/select_2/default.yaml
    message_id: true
  - code: 5031
    action_id: on_select_2
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_2/default.yaml
    message_id: false
  - code: 5022
    action_id: select_esign
    action: select
    default: FIS14/mutual-funds/2.1.0/select_esign/default.yaml
    message_id: true
  - code: 5032
    action_id: on_select_esign
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_esign/default.yaml
    message_id: false
  - code: 5023
    action_id: select_final
    action: select
    default: FIS14/mutual-funds/2.1.0/select_final/default.yaml
    message_id: true
  - code: 5033
    action_id: on_select_final
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_final/default.yaml
    message_id: false

  - code: 504
    action_id: init
    action: init
    default: FIS14/mutual-funds/2.1.0/init/default.yaml
    message_id: true
  - code: 505
    action_id: on_init
    action: on_init
    default: FIS14/mutual-funds/2.1.0/on_init/default.yaml
    message_id: false
  - code: 506
    action_id: confirm
    action: confirm
    default: FIS14/mutual-funds/2.1.0/confirm/default.yaml
    message_id: true
  - code: 507
    action_id: on_confirm
    action: on_confirm
    default: FIS14/mutual-funds/2.1.0/on_confirm/default.yaml
    message_id: false
  - code: 508
    action_id: on_status_unsolicited
    action: on_status
    default: FIS14/mutual-funds/2.1.0/on_status_unsolicited/default.yaml
    message_id: true

  - code: 509
    action_id: on_update_unsolicited
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_unsolicited/default.yaml
    message_id: false

  - code: 510
    action_id: on_update
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update/default.yaml
    message_id: false

  - code: 511
    action_id: on_status_unsolicited_payment
    action: on_status
    default: FIS14/mutual-funds/2.1.0/on_status_unsolicited_payment/default.yaml
    message_id: true

  - code: 517
    action_id: on_update_unsolicited_failed
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_unsolicited_failed/default.yaml
    message_id: true

  - code: 512
    action_id: update_payment_retry
    action: update
    default: FIS14/mutual-funds/2.1.0/update_payment_retry/default.yaml
    message_id: true

  - code: 513
    action_id: on_update_payment_retry
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_payment_retry/default.yaml
    message_id: true

  - code: 514
    action_id: on_status_unsolicited_esign
    action: on_status
    default: FIS14/mutual-funds/2.1.0/on_status_unsolicited_esign/default.yaml
    message_id: true


  - code: 518
    action_id: on_status_unsolicited_payment_success
    action: on_status
    default: FIS14/mutual-funds/2.1.0/on_status_unsolicited_payment_success/default.yaml
    message_id: true

  - code: 519
    action_id: on_update_unsolicited_success
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_unsolicited_success/default.yaml
    message_id: true

  # /***EXISTING FOLIO CALLS START*/
  - code: 520
    action_id: on_confirm_existing_folio
    action: on_confirm
    default: FIS14/mutual-funds/2.1.0/on_confirm_existing_folio/default.yaml
    message_id: false

  - code: 521
    action_id: on_init_existing_folio
    action: on_init
    default: FIS14/mutual-funds/2.1.0/on_init_existing_folio/default.yaml
    message_id: false

  - code: 522
    action_id: on_status_unsolicited_existing_folio_payment
    action: on_status
    default: FIS14/mutual-funds/2.1.0/on_status_unsolicited_existing_folio_payment/default.yaml
    message_id: true

  - code: 523
    action_id: on_update_unsolicited_existing_folio
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_unsolicited_existing_folio/default.yaml
    message_id: true

    # /***EXISTING FOLIO CALLS END*/

  - code: 524
    action_id: on_select_1_new_folio
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_1_new_folio/default.yaml
    message_id: false

  - code: 525
    action_id: on_select_2_new_folio
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_2_new_folio/default.yaml
    message_id: false

  - code: 526
    action_id: on_init_new_folio
    action: on_init
    default: FIS14/mutual-funds/2.1.0/on_init_new_folio/default.yaml
    message_id: false

  - code: 527
    action_id: on_confirm_new_folio
    action: on_confirm
    default: FIS14/mutual-funds/2.1.0/on_confirm_new_folio/default.yaml
    message_id: false

  - code: 528
    action_id: on_status_unsolicited_new_folio_payment
    action: on_status
    default: FIS14/mutual-funds/2.1.0/on_status_unsolicited_new_folio_payment/default.yaml
    message_id: true

  - code: 529
    action_id: on_update_unsolicited_new_folio
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_unsolicited_new_folio/default.yaml
    message_id: true


  - code: 530
    action_id: update_buyer_payment
    action: update
    default: FIS14/mutual-funds/2.1.0/update_buyer_payment/default.yaml
    message_id: true

  - code: 531
    action_id: on_update_buyer_payment
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_buyer_payment/default.yaml
    message_id: false

  # Redemption flows (536-543)
  - code: 545
    action_id: select_redemption
    action: select
    default: FIS14/mutual-funds/2.1.0/select_redemption/default.yaml
    message_id: true 
  - code: 536
    action_id: on_select_redemption
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_redemption/default.yaml
    message_id: false
  - code: 537
    action_id: init_redemption
    action: init
    default: FIS14/mutual-funds/2.1.0/init_redemption/default.yaml
    message_id: true
  - code: 538
    action_id: on_init_redemption
    action: on_init
    default: FIS14/mutual-funds/2.1.0/on_init_redemption/default.yaml
    message_id: false
  - code: 539
    action_id: confirm_redemption
    action: confirm
    default: FIS14/mutual-funds/2.1.0/confirm_redemption/default.yaml
    message_id: true
  - code: 540
    action_id: on_confirm_redemption
    action: on_confirm
    default: FIS14/mutual-funds/2.1.0/on_confirm_redemption/default.yaml
    message_id: false
  - code: 541
    action_id: on_update_redemption
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_redemption/default.yaml
    message_id: true
  - code: 542
    action_id: on_update_1_redemption
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_1_redemption/default.yaml
    message_id: true
  - code: 543
    action_id: on_update_2_redemption
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_2_redemption/default.yaml
    message_id: true
  - code: 544
    action_id: on_update_Cancelled
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_Cancelled/default.yaml
    message_id: true

  # SIP Creation New Folio flows (550-559)
  - code: 550
    action_id: select_SIP
    action: select
    default: FIS14/mutual-funds/2.1.0/select_SIP/default.yaml
    message_id: true
  - code: 551
    action_id: on_select_SIP
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_SIP/default.yaml
    message_id: false
  - code: 552
    action_id: select_2_SIP
    action: select
    default: FIS14/mutual-funds/2.1.0/select_2_SIP/default.yaml
    message_id: true
  - code: 553
    action_id: on_select_2_SIP
    action: on_select
    default: FIS14/mutual-funds/2.1.0/on_select_2_SIP/default.yaml
    message_id: false
  - code: 554
    action_id: init_SIP
    action: init
    default: FIS14/mutual-funds/2.1.0/init_SIP/default.yaml
    message_id: true
  - code: 555
    action_id: on_init_SIP
    action: on_init
    default: FIS14/mutual-funds/2.1.0/on_init_SIP/default.yaml
    message_id: false
  - code: 556
    action_id: confirm_SIP
    action: confirm
    default: FIS14/mutual-funds/2.1.0/confirm_SIP/default.yaml
    message_id: true
  - code: 557
    action_id: on_confirm_SIP
    action: on_confirm
    default: FIS14/mutual-funds/2.1.0/on_confirm_SIP/default.yaml
    message_id: false
  - code: 558
    action_id: on_status_unsolicited_SIP
    action: on_status
    default: FIS14/mutual-funds/2.1.0/on_status_unsolicited_SIP/default.yaml
    message_id: true
  - code: 559
    action_id: on_update_unsolicited_SIP
    action: on_update
    default: FIS14/mutual-funds/2.1.0/on_update_unsolicited_SIP/default.yaml
    message_id: false
