save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  order: "$.message.order"
  # claim_doc_url_motor: "$.message.order.documents[?(@.descriptor.code=='CLAIM_DOC')].url"