save-data:
    transaction_id: "$.context.transaction_id"
    message_id: "$.context.message_id"
    selected_items: "$.message.order.items[*]"
    order: "$.message.order"
    form_id: "$.message.order.items[*].xinput.form.id"
    E_sign_verification_status: "$..form.url"
    item: "$.message.order.items[1]"
    
