save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  billing: "$.message.order.billing"
  payments: "$.message.order.payments[*]"
  payment_collected_by: "$.message.intent.payment.collected_by"
  bap_terms_tags: "$.message.order.tags[*]"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
