save-data:
    transaction_id: "$.context.transaction_id"
    message_id: "$.context.message_id"
    order: "$.message.order"
    fullfillment_ids: "$.message.order.fulfillments[*].id"
    quote_id: "$.message.order.quote.id"
    form_id: "$.message.order.items[0].xinput.form.id"
    child_item_id: "$.message.order.items[0].id"
    parent_item_id: "$.message.order.items[0].parent_item_id"
    fulfillment_id: "$.message.order.fulfillments[0].id"
    provider_id: "$.message.order.provider.id"
    vehicle_nominee_details_form: "$..form.url"
    settlement_amount: "$.message.order.payments[0].tags[?(@.descriptor.code=='SETTLEMENT_TERMS')].list[?(@.descriptor.code=='SETTLEMENT_AMOUNT')].value"