save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  selected_provider: "$.message.order.provider"
  selected_items: "$.message.order.items[*]"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.quote"
  multiple_bureau_information_form: "$..form.url"
  quote_price: "$.message.order.quote.price.value"
  quote_id: "$.message.order.quote.id"
  principal_amount: "$.message.order.quote.breakup[?(@.title=='PRINCIPAL')].price.value"
  net_disbursed_amount: "$.message.order.quote.breakup[?(@.title=='NET_DISBURSED_AMOUNT')].price.value"
  loan_term: "$.message.order.items[0].tags[?(@.descriptor.code=='LOAN_INFO')].list[?(@.descriptor.code=='TERM')].value"
