save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  selected_items: "$.message.order.items[*]"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  # selected_fulfillment_id: "$.message.order.fulfillments[0].id"
  selected_provider: "$.message.order.provider"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
