

x-validations:
  _TESTS_:
    search:
      - _NAME_: SEARCH_CONTEXT
        action:
          - search
        domain:
          - ONDC:FIS12
        version:
          - 2.3.0
        _RETURN_:
          - _NAME_: CONTEXT_REQUIRED
            _RETURN_:
              - _NAME_: REQUIRED_CONTEXT_DOMAIN
                attr: $.context.domain
                _RETURN_: attr are present
              - _NAME_: REQUIRED_CONTEXT_LOCATION_COUNTRY_CODE
                attr: $.context.location.country.code
                _RETURN_: attr are present
              - _NAME_: REQUIRED_CONTEXT_TIMESTAMP
                attr: $.context.timestamp
                _RETURN_: attr are present
              - _NAME_: REQUIRED_CONTEXT_TRANSACTION_ID
                attr: $.context.transaction_id
                _RETURN_: attr are present
              - _NAME_: REQUIRED_CONTEXT_MESSAGE_ID
                attr: $.context.message_id
                _RETURN_: attr are present
              - _NAME_: REQUIRED_CONTEXT_VERSION
                attr: $.context.version
                _RETURN_: attr are present
              - _NAME_: REQUIRED_CONTEXT_TTL
                attr: $.context.ttl
                _RETURN_: attr are present
          - _NAME_: CONTEXT_ENUM
            _RETURN_:
              - _NAME_: VALID_CONTEXT_LOCATION_COUNTRY_CODE
                attr: $.context.location.country.code
                enumList:
                  - IND
                _RETURN_: attr any in enumList
              - _NAME_: VALID_CONTEXT_DOMAIN
                attr: $.context.domain
                enumList:
                  - ONDC:FIS12
                _RETURN_: attr all in enumList

      - _NAME_: SEARCH_INTENT
        action:
          - search
        _RETURN_:
          # - _NAME_: REQUIRED_INTENT_PAYMENT_COLLECTED_BY
          #   attr: $.message.intent.payment.collected_by
          #   enumList:
          #     - BPP
          #   _RETURN_: attr all in enumList
          - _NAME_: REQUIRED_INTENT_TAGS
            attr: $.message.intent.tags[*].descriptor.code
            enumList:
              - BAP_TERMS
            _RETURN_: attr any in enumList

    on_search:
      - _NAME_: ON_SEARCH_CONTEXT
        action:
          - on_search
        domain:
          - ONDC:FIS12
        version:
          - 2.3.0
        _RETURN_:
          - _NAME_: CONTEXT_ENUM
            _RETURN_:
              - _NAME_: VALID_CONTEXT_DOMAIN
                attr: $.context.domain
                enumList:
                  - ONDC:FIS12
                _RETURN_: attr all in enumList

      - _NAME_: ON_SEARCH_CATALOG
        action:
          - on_search
        _RETURN_:
          - _NAME_: REQUIRED_CATALOG_DESCRIPTOR_NAME
            attr: $.message.catalog.descriptor.name
            _RETURN_: attr are present
          - _NAME_: REQUIRED_PROVIDER_ID
            attr: $.message.catalog.providers[*].id
            _RETURN_: attr are present
          - _NAME_: REQUIRED_PROVIDER_ITEM_ID
            attr: $.message.catalog.providers[*].items[*].id
            _RETURN_: attr are present
          - _NAME_: REQUIRED_PROVIDER_ITEM_CODE
            attr: $.message.catalog.providers[*].items[*].descriptor.code
            enumList:
              - LOAN
            _RETURN_: attr all in enumList
          # - _NAME_: REQUIRED_ITEM_XINPUT
          #   attr: $.message.catalog.providers[*].items[*].xinput.required
          #   enumList:
          #     - "true"
          #   _RETURN_: attr all in enumList
          - _NAME_: REQUIRED_FULFILLMENT_TYPE
            attr: $.message.catalog.providers[*].fulfillments[*].type
            enumList:
              - LOAN_JOURNEY
            _RETURN_: attr all in enumList

    select:
      - _NAME_: SELECT_CONTEXT
        action:
          - select
        domain:
          - ONDC:FIS12
        version:
          - 2.3.0
        _RETURN_:
          - _NAME_: CONTEXT_ENUM
            _RETURN_:
              - _NAME_: VALID_CONTEXT_DOMAIN
                attr: $.context.domain
                enumList:
                  - ONDC:FIS12
                _RETURN_: attr all in enumList

      - _NAME_: SELECT_ORDER
        action:
          - select
        _RETURN_:
          - _NAME_: REQUIRED_PROVIDER_ID
            attr: $.message.order.provider.id
            _RETURN_: attr are present
          - _NAME_: REQUIRED_ITEM_ID
            attr: $.message.order.items[*].id
            _RETURN_: attr are present

    on_select:
      - _NAME_: ON_SELECT_ORDER
        action:
          - on_select
        _RETURN_:
          - _NAME_: REQUIRED_QUOTE
            attr: $.message.order.quote.price.value
            _RETURN_: attr are present
          - _NAME_: REQUIRED_QUOTE_BREAKUP
            attr: $.message.order.quote.breakup[*].title
            _RETURN_: attr are present

    init:
      - _NAME_: INIT_ORDER
        action:
          - init
        _RETURN_:
          - _NAME_: REQUIRED_PAYMENT_TAGS
            attr: $.message.order.payments[*].tags[*].descriptor.code
            enumList:
              - ACCOUNT_DETAILS
            _RETURN_: attr any in enumList
          - _NAME_: REQUIRED_TAG_BAP_TERMS
            attr: $.message.order.tags[*].descriptor.code
            enumList:
              - BAP_TERMS
            _RETURN_: attr any in enumList

    on_init:
      - _NAME_: ON_INIT_ORDER
        action:
          - on_init
        _RETURN_:
          - _NAME_: REQUIRED_QUOTE
            attr: $.message.order.quote.price.value
            _RETURN_: attr are present

    confirm:
      - _NAME_: CONFIRM_ORDER
        action:
          - confirm
        _RETURN_:
          - _NAME_: REQUIRED_PAYMENT_TAGS
            attr: $.message.order.payments[*].tags[*].descriptor.code
            enumList:
              - ACCOUNT_DETAILS
            _RETURN_: attr any in enumList

    on_confirm:
      - _NAME_: ON_CONFIRM_ORDER
        action:
          - on_confirm
        _RETURN_:
          - _NAME_: REQUIRED_ORDER_ID
            attr: $.message.order.id
            _RETURN_: attr are present
          - _NAME_: REQUIRED_ORDER_STATUS
            attr: $.message.order.status
            enumList:
              - ACTIVE
              - CANCELLED
              - COMPLETE
            _RETURN_: attr any in enumList

    status:
      - _NAME_: STATUS_ORDER
        action:
          - status
        _RETURN_:
          - _NAME_: REQUIRED_ORDER_ID
            attr: $.message.order_id
            _RETURN_: attr are present

    on_status:
      - _NAME_: ON_STATUS_ORDER
        action:
          - on_status
        _RETURN_:
          - _NAME_: REQUIRED_QUOTE
            attr: $.message.order.quote.price.value
            _RETURN_: attr are present

    update:
      - _NAME_: UPDATE_ORDER
        action:
          - update
        _RETURN_:
          - _NAME_: REQUIRED_UPDATE_TARGET_PATH
            attr: $.message.update_target
            enumList:
              - items
            _RETURN_: attr all in enumList

    on_update:
      - _NAME_: ON_UPDATE_ORDER
        action:
          - on_update
        _RETURN_:
          - _NAME_: REQUIRED_QUOTE
            attr: $.message.order.quote.price.value
            _RETURN_: attr are present

    cancel:
      - _NAME_: CANCEL_ORDER
        action:
          - cancel
        _RETURN_:
          - _NAME_: REQUIRED_CANCELLATION_REASON
            attr: $.message.cancellation_reason_id
            _RETURN_: attr are present

    on_cancel:
      - _NAME_: ON_CANCEL_ORDER
        action:
          - on_cancel
        _RETURN_:
          - _NAME_: REQUIRED_ORDER_STATUS_CANCELLED
            attr: $.message.order.status
            enumList:
              - CANCELLED
            _RETURN_: attr all in enumList
  _SESSION_DATA_:
    search:
      country_code: "$.context.location.country.code"