save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  submission_id : "$.message.order.xinput.form_response.submission_id"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
